[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Creativity in Music and Art: Investigating the Intersection of Technology and the Arts"
